# Generated by Django 5.0.6 on 2024-05-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("manufacturer", models.CharField(max_length=100)),
                ("serial_number", models.CharField(max_length=50, unique=True)),
                ("manufacture_date", models.DateField()),
                (
                    "warranty_information",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("category", models.CharField(max_length=50)),
            ],
        ),
    ]
